name: intl_ui
description: "A Flutter UI package that provides internationalized widgets and components for building multilingual applications."
version: 0.1.3
repository: https://github.com/Matkurban/intl_ui
homepage: https://jsontodart.cn
topics: [widgets]

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

